
package com.lshop.ws.his.tvbox;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSStbGuaranteeInfoService", targetNamespace = "http://webservice.stb.gv.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSStbGuaranteeInfoService {


    /**
     * 
     * @param mac
     * @return
     *     returns com.lshop.ws.his.tvbox.GuaranteeInfoDto
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getGuaranteeInfoByMac", targetNamespace = "http://webservice.stb.gv.com/", className = "com.lshop.ws.his.tvbox.GetGuaranteeInfoByMac")
    @ResponseWrapper(localName = "getGuaranteeInfoByMacResponse", targetNamespace = "http://webservice.stb.gv.com/", className = "com.lshop.ws.his.tvbox.GetGuaranteeInfoByMacResponse")
    public GuaranteeInfoDto getGuaranteeInfoByMac(
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

}
