
package com.lshop.ws.boss.sonsumeorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSStbResumeRecordService", targetNamespace = "com.gv.webservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSStbResumeRecordService {


    /**
     * 
     * @param startdate
     * @param page
     * @param account
     * @param year
     * @param mac
     * @param enddate
     * @param size
     * @return
     *     returns com.lshop.ws.web.resumeRecord.StbResumeDto
     */
    @WebMethod
    @WebResult(name = "outgoings", targetNamespace = "")
    @RequestWrapper(localName = "synResumeRecord", targetNamespace = "com.gv.webservice", className = "com.lshop.ws.boss.sonsumeorder.SynResumeRecord")
    @ResponseWrapper(localName = "synResumeRecordResponse", targetNamespace = "com.gv.webservice", className = "com.lshop.ws.boss.sonsumeorder.SynResumeRecordResponse")
    public StbResumeDto synResumeRecord(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "mac", targetNamespace = "")
        String mac,
        @WebParam(name = "startdate", targetNamespace = "")
        String startdate,
        @WebParam(name = "enddate", targetNamespace = "")
        String enddate,
        @WebParam(name = "year", targetNamespace = "")
        String year,
        @WebParam(name = "page", targetNamespace = "")
        Integer page,
        @WebParam(name = "size", targetNamespace = "")
        Integer size);

}
