
package test.ws.server.popularize.order.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSPPLOrderService", targetNamespace = "http://service.order.popularize.server.ws.lshop.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSPPLOrderService {


    /**
     * 
     * @param orderListNo
     * @return
     *     returns test.com.lshop.ws.server.popularize.order.service.POrderDtoResposne
     */
    @WebMethod
    @WebResult(partName = "return")
    public POrderDtoResposne getOrderDetail(
        @WebParam(name = "orderListNo", partName = "orderListNo")
        String orderListNo);

}
