
package com.lshop.ws.web.creatent.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSThreeOrderService", targetNamespace = "http://service.threeOrder.server.mall.ws.lshop.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSThreeOrderService {


    /**
     * 
     * @param threeOrder
     * @return
     *     returns com.lshop.ws.web.creatent.order.Result
     */
    @WebMethod
    @WebResult(partName = "return")
    public Result saveOrder(
        @WebParam(name = "threeOrder", partName = "threeOrder")
        ThreeOrderDto threeOrder);

    /**
     * 
     * @param startTime
     * @param email
     * @param orderNum
     * @param custName
     * @param endTime
     * @return
     *     returns com.lshop.ws.web.creatent.order.ThreeOrderSendDtoResposne
     */
    @WebMethod
    @WebResult(partName = "return")
    public ThreeOrderSendDtoResposne orderList(
        @WebParam(name = "orderNum", partName = "orderNum")
        String orderNum,
        @WebParam(name = "custName", partName = "custName")
        String custName,
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "startTime", partName = "startTime")
        String startTime,
        @WebParam(name = "endTime", partName = "endTime")
        String endTime);

    /**
     * 
     * @param orderNum
     * @param orderStatus
     * @return
     *     returns com.lshop.ws.web.creatent.order.Result
     */
    @WebMethod
    @WebResult(partName = "return")
    public Result updateOrderStatus(
        @WebParam(name = "orderNum", partName = "orderNum")
        String orderNum,
        @WebParam(name = "orderStatus", partName = "orderStatus")
        int orderStatus);

}
