
package test.ws.server.bz.order.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSOrderService", targetNamespace = "http://service.order.bz.server.ws.lshop.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSOrderService {


    /**
     * 
     * @param startTime
     * @param endTime
     * @return
     *     returns com.lshop.ws.web.bz.order.LvOrderDtoResposne
     */
    @WebMethod
    @WebResult(partName = "return")
    public LvOrderDtoResposne synAuditOrderToBZ(
        @WebParam(name = "startTime", partName = "startTime")
        String startTime,
        @WebParam(name = "endTime", partName = "endTime")
        String endTime);

}
